### ISSUE TITLE
Any document or guidance for new one to use your BLS lib?

### ISSUE THREAD

**Issue by songlinjian** [asonnino/bls#1]
I'm not a crypto guys, but I'm intereted in the propoerties of BLS for group threhold signing. I would like to build some application based on existing lib or tools on GitHub. Can you give me some suggestions how to use your code or any document of this repo?

**Comment by asonnino** [comment]
Hi songlinjian,
You can find the doc of the repo with an example here: https://bls-lib.readthedocs.io/en/latest/?badge=latest

The basic usage works as follows:
```
>>> m = [3] * 2 # messages
>>> t, n = 2, 3 # number of authorities
>>> params = setup() # generate the public parameters.
>>> (sk, vk) = ttp_keygen(params, t, n) # generate key
>>> aggr_vk = aggregate_vk(params, vk) # aggregate verification keys
>>> sigs = [sign(params, ski, m) for ski in sk] # sign
>>> sigma = aggregate_sigma(params, sigs) # aggregate credentials
>>> assert verify(params, aggr_vk, sigma, m) # verify signature
```

For threshold signing, you also need a distributed key generation algorithm (modelled by `ttp_keygen` in this repo); eg [Gennaro et. al.](https://link.springer.com/content/pdf/10.1007/3-540-48910-X_21.pdf) and [Kate et. al.](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.261.324&rep=rep1&type=pdf) If you would like to chat more about distributed keyGen, don't hesitate to contact me offline (alberto.sonnino@ucl.ac.uk).

Please note that this repo is really an "academic prototype" designed to get familiar/play with BLS and build prototypes with little effort -- do not use it for production.

**Comment by songlinjian** [comment]
Thanks I will look into it. I just play it around in a testbed.

> Hi songlinjian,
> You can find the doc of the repo with an example here: https://bls-lib.readthedocs.io/en/latest/?badge=latest
> 
> The basic usage works as follows:
> 
> ```
> >>> m = [3] * 2 # messages
> >>> t, n = 2, 3 # number of authorities
> >>> params = setup() # generate the public parameters.
> >>> (sk, vk) = ttp_keygen(params, t, n) # generate key
> >>> aggr_vk = aggregate_vk(params, vk) # aggregate verification keys
> >>> sigs = [sign(params, ski, m) for ski in sk] # sign
> >>> sigma = aggregate_sigma(params, sigs) # aggregate credentials
> >>> assert verify(params, aggr_vk, sigma, m) # verify signature
> ```
> 
> For threshold signing, you also need a distributed key generation algorithm (modelled by `ttp_keygen` in this repo); eg [Gennaro et. al.](https://link.springer.com/content/pdf/10.1007/3-540-48910-X_21.pdf) and [Kate et. al.](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.261.324&rep=rep1&type=pdf) If you would like to chat more about distributed keyGen, don't hesitate to contact me offline ([alberto.sonnino@ucl.ac.uk](mailto:alberto.sonnino@ucl.ac.uk)).
> 
> Please note that this repo is really an "academic prototype" designed to get familiar/play with BLS and build prototypes with little effort -- do not use it for production.

**Comment by songlinjian** [comment]
After I installed bls-lib. I run the basic-usage code you proposed. There is a error msg :

File "/usr/local/lib/python3.5/dist-packages/bls/utils.py", line 36, in hash
    Cstring = b",".join([str(x) for x in elements])
TypeError: sequence item 0: expected a bytes-like object, str found
