### ISSUE TITLE
hash function not compatible with python3 

### ISSUE THREAD

**Issue by wyzd03105** [asonnino/bls#2]
I hack the code like this:

def hash(elements):
  """ generates a Bn hash by hashing a number of EC points """
  """ Cstring = b",".join([str(x) for x in elements]) # not compatible with python3 """
  Cstring = ",".join([str(x) for x in elements]).encode()  # compatible now
  return  sha256(Cstring).digest()

**Comment by asonnino** [comment]
Thanks!
